name: action-is-biweekly
author: Nicholas J. Fantozz
description: Determine if is a biweekly run
inputs:
  comparison-date:
    description: The time to compare the running build against (YYYY-MM-DD)
    required: true
  fail-on-error:
    description: Fail the workflow if this is not a bi-weekly run
    default: true
    required: false
outputs:
  is-biweekly:
    description: true/false if this is a biweekly run
    value: ${{ steps.is-biweekly.outputs.is-biweekly }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.comparison-date }}
    - ${{ inputs.fail-on-error }}