name: Test fail on error - Runs daily, successful once every 2 weeks

on:
  workflow_dispatch:
  schedule:
  - cron: 0 12 * * * # Everyday at noon

jobs:
  test-biweekly-action:
    runs-on: ubuntu-latest
    steps:
    - name: Test if this is a biweekly run, fail if not
      id: is-biweekly
      uses: nick11703/action-is-biweekly@main
      with:
        comparison-date: '2024-06-28'
        fail-on-error: true
      
    - name: Output if not an error
      run:  |
        echo 'You will see this only when the test is a biweekly run. All others will be failed builds.' >> $GITHUB_STEP_SUMMARY
